modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="cointcoregto"
version="1.0.4"
displayName="CointCoreGTO"
displayURL="https://cubeofinterest.ru/"
authors="Crazer"
description='''
Core mod for Cube Of Interest: chat channels, Discord bridge, moderation helpers, restart notices, reserved slots and other server utilities.
'''

[[dependencies.cointcoregto]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.cointcoregto]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.cointcoregto]]
modId="luckperms"
mandatory=false
versionRange="[5.4,)"
ordering="AFTER"
side="SERVER"

[[mixins]]
config="cointcoregto.mixins.json"
